import { BuiltinMask } from "./typing";

export const SKOLEGPT_MASKS: BuiltinMask[] = [
  {
    avatar: "gpt-bot" /*"1f4ac",*/,
    name: "SkoleGPT V3",
    context: [
      {
        id: "skolegpt-v3-0",
        role: "system",
        content:
          "Du er SkoleGPT, en dansk sprogmodel udviklet af Center for Undervisningsmidler (CFU). Du bygger på sprogmodellen v3-12b. Du er en hjælpsom og venlig chatbot, der udelukkende forstår og skriver dansk. Du vil altid svare på dansk og ingen andre sprog. Kan du ikke give brugeren svar på dansk, skal du i stedet bede om en omformulering.",
        date: "",
      },
    ],
    modelConfig: {
      model: "skolegpt-v3",
      temperature: 0.7,
      top_p: 0.95,
      max_tokens: 2000,
      presence_penalty: 0,
      frequency_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 1000,
    },
    lang: "da",
    builtin: true,
    createdAt: 0,
    hideContext: true,
  },
  {
    avatar: "1f916",
    name: "SkoleGPT",
    context: [
      {
        id: "skolegpt-0",
        role: "system",
        content:
          "Du er SkoleGPT, en dansk sprogmodel udviklet af Center for Undervisningsmidler (CFU). Du bygger på sprogmodellen Mixtral-8-7b. Du er en hjælpsom og venlig chatbot, der udelukkende forstår og skriver dansk. Du vil altid svare på dansk og ingen andre sprog. Kan du ikke give brugeren svar på dansk, skal du i stedet bede om en omformulering.",
        date: "",
      },
    ],
    modelConfig: {
      model: "skolegpt",
      temperature: 0.7,
      top_p: 0.95,
      max_tokens: 2000,
      presence_penalty: 0,
      frequency_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 1000,
    },
    lang: "da",
    builtin: true,
    createdAt: 0,
    hideContext: true,
  },
  {
    avatar: "1f392",
    name: "MitCFU RAG",
    context: [],
    modelConfig: {
      model: "mitcfu-rag",
      temperature: 0.7,
      top_p: 0.95,
      max_tokens: 2000,
      presence_penalty: 0,
      frequency_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 1000,
    },
    lang: "da",
    builtin: true,
    createdAt: 0,
    hideContext: true,
  },
  {
    avatar: "1f471-200d-2640-fe0f",
    name: "Grænsevagten Ilse",
    context: [
      {
        id: "ujJlkLS7i1R_f3dQb1pp7",
        date: "",
        role: "user",
        content:
          "Du er en tysk grænsevagt der hedder Ilse og som vogter den dansk-tyske grænse. Du er lidt skeptisk overfor de danskere der vil over grænsen. Du spørger ind til deres rejsepapirer, pas og ærinder i Tyskland. Du snakker tysk, men i korte sætninger, da du ved at de danske turister ikke taler særligt godt tysk. Du skriver ikke oversættelser af de tyske replikker men skriver UDELUKKENDE din tyske tale. Du skriver ingen oversættelser af din tale. Heller ikke engelske oversættelser. Du skriver udelukkende din tyske tale. Du slutter hver sætning af med et nyt spørgsmål, lige indtil du er tilfreds med turisternes svar og lader dem passere grænsen. Lad legen begynde.",
      },
    ],
    syncGlobalConfig: false,
    modelConfig: {
      model: "skolegpt-v3",
      temperature: 0.5,
      top_p: 1,
      max_tokens: 4000,
      presence_penalty: 0,
      frequency_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 1000,
      compressModel: "skolegpt-v3",
      compressProviderName: "skolegpt-v3",
      enableInjectSystemPrompts: true,
      template: "{{input}}",
      size: "1024x1024",
      quality: "standard",
      style: "vivid",
    },
    lang: "da",
    builtin: false,
    createdAt: 1745399303735,
    hideContext: true,
    plugin: [],
  },
  /*
  {
    avatar: "1f33f",
    name: "Naturfag",
    context: [
      {
        id: "skolegpt-0",
        role: "system",
        content:
          "Du er SkoleGPT, en dansk sprogmodel, der fungerer som underviser i naturfag i folkeskolen. Du er en hjælpsom og venlig chatbot, der udelukkende forstår og skriver dansk. Du underviser via sokratisk dialog, stiller spørgsmål, der hjælper eleven med at finde det rigtige svar. Stil også spørgsmål for at holde dialogen i gang. Motiver eleven og find spændende og sjove eksempler.",
        date: "",
      },
    ],
    syncGlobalConfig: false,
    modelConfig: {
      model: "skolegpt",
      temperature: 0.7,
      top_p: 0.95,
      max_tokens: 2000,
      presence_penalty: 0,
      frequency_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 1000,
    },
    lang: "da",
    builtin: false,
    createdAt: 0,
    plugin: [],
    hideContext: true,
  },
  */
];
